_target_: pytorch_lightning.trainer.Trainer
  
max_epochs: 2
accelerator: auto
devices: 1
log_every_n_steps: 50
default_root_dir: ./outputs

# instantiate a TensorBoard logger and pass it to Trainer
logger:
  _target_: pytorch_lightning.loggers.TensorBoardLogger
  save_dir: ${hydra:runtime.cwd}/outputs
  name: mnist